### ISSUE TITLE
BUG: Error connecting to dedicated server.

### ISSUE THREAD

**Issue by minie0** [Lightman314/LightmansCurrencyFabric#1]
### Minecraft Version

1.19.2

### Fabric Version

1.19.2

### Lightman's Currency Version

1.19.2

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

jei, journeymap, iris shader

### Describe the bug

Hi, Thank u for 'LC mod' developers!
Sorry, but it doesn't works on 'fabric 1.19.2'
Error message ;invalid player data;

I deleted 'server folder; world\player data\;.
But It hasn't been solved.
It works fine than except 'LC mod'

What's the problem...?
How can i do?

### To Reproduce

4. See error.

### Screenshots/Logs/Crash Reports

![untitle](https://user-images.githubusercontent.com/120258326/206857736-895c0bed-a590-4dd1-839f-d7e598c5a391.png)

**Comment by Lightman314** [comment]
Please provide the *entire* latest.log file as requested in the issue report. Also, the steps to reproduce is invalid, as I need to know what steps you took to encounter said "invalid player data". Are you trying to join a server, or just starting a single-player world as your "Environment Type" input states?

ALSO- `1.19.2` is not a valid LC version number (currently `1.0.0.0` is the only LC fabric version released), NOR is it a valid Fabric Loader version. Please update these numbers as appropriate.

**Comment by Lightman314** [comment]
Fixed in v1.0.0.1.

**Comment by minie0** [comment]
[latest.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/10200741/latest.log)


Sorry, I rewrite this report.

Minecraft Ver. : 1.19.2
Fabric Ver. : 0.14.11
LC MOD Ver. : 1.0.0.1

I created fabric server. Not single play.
Attach the entire 'latest.log'. 
My server is operate normally, But not works LC MOD.

I am extremely grateful for your help.
