### ISSUE TITLE
BUG: Can't craft wallets because it wants forge:leather

### ISSUE THREAD

**Issue by getkirill** [Lightman314/LightmansCurrencyFabric#11]
### Minecraft Version

1.19.2

### Fabric Version

0.14.14

### Lightman's Currency Version

v1.19.2-1.0.0.6

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

FTB Teams, Chunks, Library
Architectury API, Fabric API
Luckperms
...some other mods

### Describe the bug

you can't craft wallets. it wants nonexistent forge:leather

### To Reproduce

1. new survival world
2. get leather, get copper coin
3. try crafting wallet
4. it doesn't work

### Screenshots/Logs/Crash Reports

https://mclo.gs/5Te2uDr

**Comment by getkirill** [comment]
i will probably make a quick pr because i probably know how to fix this

**Comment by Lightman314** [comment]
I'll have a build that fixes this out later today or early tomorrow. Thanks for letting me know about it though.

**Comment by Lightman314** [comment]
Fixed in v1.0.0.7.
