### ISSUE TITLE
BUG: Trading terminals aren't working

### ISSUE THREAD

**Issue by MintKeyphase** [Lightman314/LightmansCurrencyFabric#14]
### Minecraft Version

1.19.2

### Fabric Version

0.14.12

### Lightman's Currency Version

1.19.2

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

- additionalstructures 4.1.1
	- adorn 3.8.0+1.19.2
	- advanced_runtime_resource_pack 0.6.2 via automobility
	- ae2 12.8.5
	- ae2wtlib 12.0.2-alpha
	- alloy_forgery 2.0.17+1.19
	- architectury 6.4.62
	- automobility 0.4.1+1.19.2-fabric
	- blast 1.10
	- blue_endless_jankson 1.2.1 via owo
	- botarium 1.8.2
	- cardinal-components-base 5.0.0-beta.1 via mythicmetals
	- cardinal-components-entity 5.0.0-beta.1 via mythicmetals
	- citresewn 1.1.2+1.19.2
	- citresewn-defaults 1.1.2+1.19.2 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- collective 6.48
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 20 via geckolib3
	- com_github_llamalad7_mixinextras 0.1.1 via porting_lib_base
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_typesafe_config 1.4.1 via croptopia
	- computercraft 1.101.2
	- craftingbench 0.4-BETA+1.19
	- create 0.5.0g-796+1.19.2
	- createaddition ${version}
	- createdeco 1.2.12-1.19.2
	- croptopia 2.1.2
	- dehydration 1.3.3
	- diggusmaximus 1.5.8-1.19
	- dripstone_fluid_lib 2.0.1 via milk
	- emi 0.7.0+1.19.2
	- enchanted-vertical-slabs 1.6.2
	- environmentz 1.3.5
	- error_notifier 1.0.9 via roughlyenoughitems
	- extendedflywheels 1.19.2-0.5.0.g-1.2.5.1
	- eyemod 2.1.1
	- fabric-api 0.70.0+1.19.2
	- fabric-api-base 0.4.14+6e0787e690 via fabric-api
	- fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.21+4d0d570390 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.23+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.4+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.14+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.10+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.31+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.39+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.4+ad31814d90 via fabric-api
	- fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.32+4d0d570390 via fabric-api
	- fabric-events-lifecycle-v0 0.2.32+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.2+fa140d5990 via fabric-api
	- fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.24+aaaf9d3390 via fabric-api
	- fabric-keybindings-v0 0.2.22+df3654b390 via fabric-api
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.20+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.9+6e0787e690 via fabric-api
	- fabric-networking-v0 0.3.26+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.1.4+4d0d570390 via fabric-api
	- fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
	- fabric-registry-sync-v0 0.9.30+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.1.1+6e0787e690 via fabric-api
	- fabric-renderer-indigo 0.6.18+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.23+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
	- fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
	- fabric-rendering-v0 1.1.26+df3654b390 via fabric-api
	- fabric-rendering-v1 1.12.0+08b73de490 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
	- fabric-screen-api-v1 1.0.31+4d0d570390 via fabric-api
	- fabric-screen-handler-api-v1 1.3.5+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.23+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.4+4d0d570390 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricloader 0.14.12
	- fake-player-api 0.5.0 via create
	- fiber 0.23.0-2 via patchouli
	- flywheel 0.6.8-1 via create
	- forge_tags 3.0 via porting_lib
	- forgeconfigapiport 4.2.6 via create
	- geckolib3 3.1.38
	- hdskins 6.6.1
	- hwg 1.2.10
	- indium 1.0.7+mc1.19
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- io_netty_netty-codec-http 4.1.77.Final via computercraft
	- java 17
	- jsonem 0.1.2+1.19 via automobility
	- kirin 1.12.0 via minelp
	- kyrptconfig 1.4.14-1.19 via diggusmaximus
	- lightestlamp 3.0.0f
	- lightmanscurrency 1.19.2-1.0.0.6
	- magna 1.8.0-1.19 via modern_industrialization
	- mcwbridges 1.0.6
	- mcwdoors 1.0.8
	- mcwfences 1.0.7
	- mcwtrpdoors 1.0.8
	- mcwwindows 2.1.2
	- milk 1.0.51 via create
	- minecraft 1.19.2
	- minelp 4.6.2
	- mininggadgets ${version}
	- mm 2.3 via porting_lib_base
	- modern_industrialization 1.4.1
	- modmenu 4.1.2
	- mson 1.6.1 via minelp
	- mythicmetals 0.16.4+1.19.2
	- noindium 1.1.0+1.19 via ae2
	- omega-config 1.0.8 via magna
	- org_apache_httpcomponents_httpmime 4.3.2 via hdskins
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- org_squiddev_cobalt 0.5.5 via computercraft
	- owo 0.8.5+1.19
	- pandamc_concreteplus 1.9.5
	- patchouli 1.19.2-77-FABRIC
	- peripheralium 0.4.17-1.19.2
	- playerabilitylib 1.6.0 via modern_industrialization
	- porting_lib 2.1.623+1.19.2 via create
	- porting_lib_accessors 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_attributes 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_base 2.1.623+1.19.2 via porting_lib
	- porting_lib_common 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_constants 2.1.623+1.19.2 via porting_lib_attributes
	- porting_lib_entity 2.1.623+1.19.2 via porting_lib
	- porting_lib_extensions 2.1.623+1.19.2 via porting_lib_transfer
	- porting_lib_lazy_registration 2.1.623+1.19.2 via porting_lib
	- porting_lib_model_generators 2.1.623+1.19.2 via porting_lib
	- porting_lib_model_loader 2.1.623+1.19.2 via porting_lib_obj_loader
	- porting_lib_models 2.1.623+1.19.2 via porting_lib
	- porting_lib_networking 2.1.623+1.19.2 via porting_lib
	- porting_lib_obj_loader 2.1.623+1.19.2 via porting_lib
	- porting_lib_transfer 2.1.623+1.19.2 via porting_lib
	- reach-entity-attributes 2.3.0 via create
	- registrate-fabric 1.1.44-MC1.19.2 via create
	- resourcefulconfig 1.0.19
	- resourcefullib 1.1.22
	- roughlyenoughitems 9.1.580
	- satin 1.8.0 via environmentz
	- serialization_hooks 0.3.26 via porting_lib_base
	- sodium 0.4.2+build.16
	- team_reborn_energy 2.2.0 via botarium
	- travelersbackpack 1.19.2-8.2.13
	- trinkets 3.4.0
	- turtlematic 0.5.2
	- unicopia 1.0.0-beta.28
	- whipdashing 1.0.4+1.19.x

### Describe the bug

The trading interface of network traders and auction house won't show up in trading terminal

### To Reproduce

open a server
put down a trader
try using a trading terminal

### Screenshots/Logs/Crash Reports

Well it just DOESN'T WORK, nothing shows up

**Comment by Lightman314** [comment]
Please list the _exact_ version of LC that you are using (e.g. LC 1.19.2-1.0.0.9). Also, please try updating as this exact issue was fixed in LC Fabric v1.0.0.9.

**Comment by Lightman314** [comment]
I see now that the LC version is listed in your "other relevant mods list. Please update from v1.0.0.6 to v1.0.0.9a to fix your issue, and please **always** update to the latest version of the mod before reporting issues as they may already have been fixed in newer versions.
