### ISSUE TITLE
BUG: Can't get payment (what's inside the selling block)

### ISSUE THREAD

**Issue by Mailhingg** [Lightman314/LightmansCurrencyFabric#15]
### Minecraft Version

1.19.2

### Fabric Version

0.14.17

### Lightman's Currency Version

latest

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

we use a lot of mods, though we are not getting any errors or anything neither client side, neither server side

### Describe the bug

basically you can click to get whatever coins are inside the block from previous sell, it will take these and clear them (mneaning you can't get them anymore), but instead of giving them in your inventory you just don't get anything :/

### To Reproduce

to be honest i think it's related to our config, or we might have no understand something. So i don't really know. Maybe this is a known issue with certain mods.?

### Screenshots/Logs/Crash Reports

https://i.gyazo.com/36997d2ebdf5fda222b4aa139dba90ab.mp4

**Comment by Lightman314** [comment]
I've tested and confirmed that it isn't working properly, that said it does let you collect properly if you have a wallet equipped (as it'll put the money in your wallet), so I'd recommend doing that until I can figure out why this isn't working properly.

**Comment by Lightman314** [comment]
Should be fixed in v1.0.0.10
