### ISSUE TITLE
BUG: Wallet slot renders over everything else displayed

### ISSUE THREAD

**Issue by fzzyhmstrs** [Lightman314/LightmansCurrencyFabric#16]
### Minecraft Version

1.19.2

### Fabric Version

0.14.19

### Lightman's Currency Version

1.19.2-1.0.0.10

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

The Wallet Slot draws on top of everything, including tooltips. From my poking around, this is an artifact of using the `afterRender` event, which is after everything, including the tooltip, is drawn.

here is an example armor tooltip with the wallet slot covering things up.

![image](https://user-images.githubusercontent.com/72876796/235313972-42ef2f1e-e9bd-417a-8019-4d8f204ddab6.png)

### To Reproduce

Open player inventory with LC installed.

Try to read an item tooltip in the general vicinity of the slot.

### Screenshots/Logs/Crash Reports

Screenshot example posted above.

**Comment by Lightman314** [comment]
Should be fixed in v1.0.1.0.
