### ISSUE TITLE
BUG: Client Crashes on Timefall SMP Modpack

### ISSUE THREAD

**Issue by fzzyhmstrs** [Lightman314/LightmansCurrencyFabric#17]
### Minecraft Version

1.19.2

### Fabric Version

0.14.19

### Lightman's Currency Version

1.19.2-1.0.0.10

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

I don't see any other mods involved in the stacktrace.

### Describe the bug

Getting a client-side crash when people are interacting with shop blocks, at least with a vending machine. No positive confirmation on whether there are other blocks involved.

Player crashes when accessing the shop block. Some example descriptions:
* " was while opening a vending machine"
* "Buying 2 bag of souls books from [players] shop"

### To Reproduce

Not entirely sure the exact steps needed to reproduce. It doesn't happen consistently every time the vending machine or other blocks are interacted with. In general: Happening in the "Timefall SMP" modpack. Player is interacting with a vending machine and maybe other types of shop blocks. Client crashes.

### Screenshots/Logs/Crash Reports

Crash example 1:
[new_crash_5523.txt](https://github.com/Lightman314/LightmansCurrencyFabric/files/11409901/new_crash_5523.txt)

Crash example 2:
[message(2).txt](https://github.com/Lightman314/LightmansCurrencyFabric/files/11409902/message.2.txt)

**Comment by Lightman314** [comment]
I can't say I know why this is happening (the update packet from the server is probably being processed at the same time as the trader is being rendered would be my assumption), but I can prevent this error from happening easily enough. Should be fixed in the next update.

**Comment by Lightman314** [comment]
Should be fixed in v1.0.1.0.
