### ISSUE TITLE
Feature: Update mod to 1.20.1

### ISSUE THREAD

**Issue by lostopkk** [Lightman314/LightmansCurrencyFabric#18]
### Minecraft Version

1.19.2

### Fabric Version

Newest Fabric

### Lightman's Currency Version

0.14.10 1.19.2

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Update the mod to newest version

### To Reproduce

Update

### Screenshots/Logs/Crash Reports

Update

**Comment by Lightman314** [comment]
I intend to update all of my mods to 1.20 soon, however I don't have a lot of free time at the moment so it may take a while.

**Comment by lostopkk** [comment]
take your time man, thank you!

**Comment by Lightman314** [comment]
Mod is now available for 1.20.1. Closing the ticket.

**Comment by lostopkk** [comment]
> Mod is now available for 1.20.1. Closing the ticket.

Thanks! will be release in modrinth equal forge?(sorry for bad english)

**Comment by Lightman314** [comment]
The files uploaded to modrinth are the same as those loaded to curseforge, and will be posted at the same time...
