### ISSUE TITLE
BUG: Missing textures on coinpiles

### ISSUE THREAD

**Issue by transcental** [Lightman314/LightmansCurrencyFabric#22]
### Minecraft Version

1.20.1

### Fabric Version

0.14.22

### Lightman's Currency Version

1.20.1-1.0.1.0

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

The top textures are not present for coinpiles.
I've not screenshotted it, but the particle textures are also missing.

### To Reproduce

1. Load the mod
2. Get coinpiles
3. Place them in the world.

### Screenshots/Logs/Crash Reports

![image](https://github.com/Lightman314/LightmansCurrencyFabric/assets/83948303/6d324256-92e5-4420-89e8-14772799d2aa)
Logs: https://mclo.gs/tXQHLdD

**Comment by chronosacaria** [comment]
This is due to a rogue `s` in the model file. The file states `items` when it should be `item`

**Comment by transcental** [comment]
Ah, that sounds like a simple enough fix. I may PR that if it's not done when I get some free time.

**Comment by Lightman314** [comment]
This is already fixed in dev, I was just waiting until I finished my work on LC 2.1.2.4 before I start tackling the LC Fabric issues.
Update should hopefully be out soon fixing this and other LC Fabric issues.

Probably also going to give the coin pile/blocks the new updated model/textures I gave LC proper in the latest update.

**Comment by transcental** [comment]
Awesome, looking forward to it

**Comment by Lightman314** [comment]
Fixed in LC Fabric v1.0.1.1. While I was fiddling with the models I also went ahead and updated most if not all of the other changed models/textures to their latest forms in LC Forge.
