### ISSUE TITLE
BUG: Recipes not working

### ISSUE THREAD

**Issue by orb1n** [Lightman314/LightmansCurrencyFabric#25]
### Minecraft Version

1.20.1

### Fabric Version

0.14.25

### Lightman's Currency Version

1.0.1.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

The crafting recipe for the [Upgrade Smithing Template](https://github.com/Lightman314/LightmansCurrencyFabric/blob/main/src/main/resources/data/lightmanscurrency/recipes/upgrades/upgrade_smithing_template_create.json) is not working probably because the forge:nuggets/iron tag doesn't exist.
EDIT: Some other recipes aren't working too because the forge tags don't exist

### To Reproduce

1. Use a crafting table
2. Put a trading core in the middle and surround it with iron nuggets
3. See that nothing happens

### Screenshots/Logs/Crash Reports

I think you don't need that.

**Comment by Lightman314** [comment]
Noted. I'll do a thorough look through my recipes before I upload my next LC Fabric update (which should be happening soon)

**Comment by Lightman314** [comment]
Fixed in LC Fabric v1.0.2.0. Thank you for reporting!
