### ISSUE TITLE
i would love to see the slot machines in the fabric version, could you bring them back to 1.19.2?

### ISSUE THREAD

**Issue by KalceP** [Lightman314/LightmansCurrencyFabric#26]
i wanted to make a lottery system for my server, and the best mod adding the slot machines was lightman's currency, i check the creative menu, and there's no sign of it

i would want the slot machine to be ported to the fabric versions, 1.19.2+

i have no other alternatives, just the slot machine

no additional context, just a wish for the slot machine

**Comment by Lightman314** [comment]
Already announced on discord that this was going to happen.
