### ISSUE TITLE
BUG:  Slots Machine Dupe

### ISSUE THREAD

**Issue by Majurad** [Lightman314/LightmansCurrencyFabric#27]
### Minecraft Version

1.20.1

### Fabric Version

0.15.3

### Lightman's Currency Version

1.20.1-1.0.2.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

I created a slot machine to act just like a real slot machine. I gave it a 5 iron cost and put the possible loot as the copper, iron, gold, emerald, and diamond coins. I set up the percent chance for each to be landed on and put 1 diamond in for it to pay out from. I then emptied my wallet and inventory and had enough for 1 roll. After the roll was over  and I compared, it had generated more money than the total of its inventory of 1 diamond + the 5 iron cost. 

### To Reproduce

1.Get a slot Machine
2.Place down anywhere
3.Set up 1 of each Coin, up to diamond as the possible entries, may have to toy with weights
4.Set up a Cost, I set 5 iron
5.Place 1 diamond in so the machine reads that it can roll
6.Make sure you have no other coins in inventory or wallet and make sure bank is not linked
7. Roll and observe, repeat as necessary 

### Screenshots/Logs/Crash Reports

[server249807_14_Jan_2024_3_45_12.zip](https://github.com/Lightman314/LightmansCurrencyFabric/files/13930960/server249807_14_Jan_2024_3_45_12.zip)

**Comment by Lightman314** [comment]
Fixed in v1.0.2.1a. Thank you for reporting!
