### ISSUE TITLE
BUG: Missing Select Recipes

### ISSUE THREAD

**Issue by PastellePixie** [Lightman314/LightmansCurrencyFabric#29]
### Minecraft Version

1.20.1

### Fabric Version

15.9

### Lightman's Currency Version

1.0.2.3a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

REI perhaps?

### Describe the bug

Recipes missing for certain items
(mangrove, bamboo, cherry shelves and card displays)

### To Reproduce

Use mod in survival

### Screenshots/Logs/Crash Reports

![Missing Recipes](https://github.com/Lightman314/LightmansCurrencyFabric/assets/71416115/b171b4b1-0e1c-4cfd-87b6-ab6eea6e293d)

**Comment by Lightman314** [comment]
Fixed in LC Fabric v1.0.2.4
Thank you for reporting!
