### ISSUE TITLE
Modpack Authurisation On Modrinth

### ISSUE THREAD

**Issue by Amberslice** [Lightman314/LightmansCurrencyFabric#30]
### Minecraft Version

1.20.1

### Fabric Version

0.15.7

### Lightman's Currency Version

1.0.2.2a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Im looking to host a modpack on Modrinth, we love using lightmans currency and we would love to be able to include your mod into our modpack.

### To Reproduce

..

### Screenshots/Logs/Crash Reports

..

**Comment by Amberslice** [comment]
https://modrinth.com/modpack/sillysquirrels this is the modpack

**Comment by Lightman314** [comment]
LC Fabric is already published on Modrinth, it's just sharing a page with LC Forge since modrinth doesn't let us have seperate pages for different modloaders.

Authorization is unnecessary.
