### ISSUE TITLE
BUG: Incompatibility with Small Ship

### ISSUE THREAD

**Issue by YOUNIN15** [Lightman314/LightmansCurrencyFabric#32]
### Minecraft Version

1.20.1

### Fabric Version

0.15.11

### Lightman's Currency Version

1-1.0.2.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

smallships-fabric-1.20.1-2.0.0-b1.2

### Describe the bug

Apparently small ships and Lightman's Currency can't run together, when you run minecraft it just crashes and won't start, I have tried the two mods separately and they work fine, but when you load them both together there is just an error.

### To Reproduce

1. Run minecraft
2. Crash

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/15321984/latest.log)

**Comment by Lightman314** [comment]
*Should* be fixed in LC Fabric v1.0.2.4
Thank you for reporting!
