### ISSUE TITLE
BUG: Unloading chunk causes visual bug

### ISSUE THREAD

**Issue by thesleever** [Lightman314/LightmansCurrencyFabric#34]
### Minecraft Version

1.20.1

### Fabric Version

0.5.11

### Lightman's Currency Version

1.0.2.3a-1.20.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

When you unload a chunk that has an Item Network Trader placed in it, on the client side it will look like the trade is not linked, even though it is linked.

### To Reproduce

1. Place an Item Network Trader, select a trade
2. Unload the chunk ("/tp ~1000 ~ ~", for example)
3. Return to the chunk and open first page of Network Trader

https://github.com/Lightman314/LightmansCurrencyFabric/assets/57146578/dbad86dc-240e-4256-94e4-6e034b4db04d

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/15485793/latest.log)

**Comment by Lightman314** [comment]
Same issue as #35

**Comment by Lightman314** [comment]
Fixed in LC Fabric v1.0.2.4
Thank you for reporting!
