### ISSUE TITLE
BUG: Gamerules seem to not be working

### ISSUE THREAD

**Issue by GingerPopper** [Lightman314/LightmansCurrencyFabric#36]
### Minecraft Version

1.20.1

### Fabric Version

0.15.11

### Lightman's Currency Version

1.20.1-1.0.2.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Gamerules seem to not be working (on the fabric version at least).
I setup two instances, one forge and one fabric to test and the forge version gamerules work without issue.
The fabric version seems to completely ignore the gamerules, as you both lose your wallet with keepWallet set to true and you don't lose coins on death with the coinDropPercent set to a value higher than 0.

I tested some older versions, including 1.20.1-1.0.2.2 where keepWallet works, however coinDropPercent still doesn't work correctly. It seems the whole issue only affects 1.20.1-1.0.2.3 after trinket compatibility was added.

### To Reproduce

1. Create a new fabric instance for testing
2. Install lightman's currency fabric and trinket.
3. Create a world and set the keepWallet gamerule to true and the coinDropPercent to any value higher than 0.

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/user-attachments/files/15802176/latest.log)

**Comment by Lightman314** [comment]
Fixed in LC Fabric v1.0.2.4
Thank you for reporting!
