### ISSUE TITLE
BUG: Improper Rendering of Vending Machines

### ISSUE THREAD

**Issue by VictoriaMoonlight** [Lightman314/LightmansCurrencyFabric#38]
### Minecraft Version

1.20.1

### Fabric Version

0.15.11

### Lightman's Currency Version

1.20.1-1.0.2.3a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Both variants (regular/large) of vending machines render improperly when their bottom face is completely touching another block, causing the top of the block(s) the vending machine is on to become invisible and create an x-ray window in the floor.

### To Reproduce

1. Open Minecraft World
2. Place vending machine on grass block (or any other block with complete collision; **not** soul sand, honey, etc.)

### Screenshots/Logs/Crash Reports

![2024-07-09_17 38 30](https://github.com/Lightman314/LightmansCurrencyFabric/assets/141262521/1a023421-bc41-43bb-b5fb-76dbc7f3fdc0)
![2024-07-09_17 38 40](https://github.com/Lightman314/LightmansCurrencyFabric/assets/141262521/08184aa9-1062-42b9-914d-184d23d1802e)

**Comment by Lightman314** [comment]
Fixed in LC Fabric v1.0.2.4
Thank you for reporting!
