### ISSUE TITLE
BUG: Error connecting to dedicated server.

### ISSUE THREAD

**Issue by minie0** [Lightman314/LightmansCurrencyFabric#4]
### Minecraft Version

1.19.2

### Fabric Version

0.14.11

### Lightman's Currency Version

1.19.2.1.0.0.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

fabric-api-0.68.0+1.19.2.jar
lightmanscurrency_fabric-1.19.2-1.0.0.1.jar

### Describe the bug

![Untitle](https://user-images.githubusercontent.com/120258326/207201996-6596d582-4e54-4529-8efe-01fbe695958f.png)

### To Reproduce

Hi, I really want to use LC mod.
I tried to find problem, But I didn't. Sorry.

Dedicated server disconnected.
I'll attatch a error message and latest log.

I apologize for bothering you when you are busy.

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/10213404/latest.log)

**Comment by Lightman314** [comment]
I have tested and am unable to replicate. Are you certain that the mod is installed on both the server and the client?

**Comment by minie0** [comment]
I did it at last!
I reinstall a Minecraft, Fixed it.

I didn't know the exact reason, But you don't have to worry any more.
I'll use it thankfully.
