### ISSUE TITLE
BUG: Armordisplay Crash

### ISSUE THREAD

**Issue by minie0** [Lightman314/LightmansCurrencyFabric#5]
### Minecraft Version

1.19.2

### Fabric Version

0.14.11

### Lightman's Currency Version

1.19.2.1.0.0.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

![MODS](https://user-images.githubusercontent.com/120258326/207328188-6496f499-39cf-4d22-8619-2071057dd41c.png)
![MODS2](https://user-images.githubusercontent.com/120258326/207328195-acbfe380-cef9-4e32-a042-b042df023a25.png)

### Describe the bug

Client closing when I placed 'Armor display' item

### To Reproduce

At first, to receive a error message as below every second when I placed the 'Armordisplay' item.
;[Netty Server IO #6/INFO]: Received server packet of type 'lightmanscurrency:blockentity_armordisplay_request_stand'!;

I retried to place the 'Armordisplay' After client reboot, But client closed with crash.

### Screenshots/Logs/Crash Reports

[crash-2022-12-13_22.10.57-client.txt](https://github.com/Lightman314/LightmansCurrencyFabric/files/10218345/crash-2022-12-13_22.10.57-client.txt)
[latest.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/10218346/latest.log)

**Comment by Lightman314** [comment]
Should be fixed in v1.0.0.3
