### ISSUE TITLE
BUG: Account deposit and withdrawal

### ISSUE THREAD

**Issue by minie0** [Lightman314/LightmansCurrencyFabric#6]
### Minecraft Version

1.19.2

### Fabric Version

0.14.11

### Lightman's Currency Version

1.19.2.1.0.0.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

none

### Describe the bug

Thank you.
It's me again, Sir.

Can I use account on this version?
Doesn't working account function. 
It didn't activation the menu(deposit and withdrawal) when I insert a coin.

I attach a video file(zip).

I'm sorry if I used it wrong.

### To Reproduce

[c2022-12-14 09-50-00 - 복사본.zip](https://github.com/Lightman314/LightmansCurrencyFabric/files/10223255/c2022-12-14.09-50-00.-.zip)

### Screenshots/Logs/Crash Reports

none

**Comment by Lightman314** [comment]
Fixed in v1.0.0.4. Thank you for reporting.
