### ISSUE TITLE
BUG: Not working Paygate & Tickets & Kiosk

### ISSUE THREAD

**Issue by minie0** [Lightman314/LightmansCurrencyFabric#7]
### Minecraft Version

1.19.2

### Fabric Version

0.14.11

### Lightman's Currency Version

1.19.2.1.0.0.4

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

None

### Describe the bug

Hello, sir.

I'm satisfied with LC mods.
I want to use more function, too. But It isn't working.

Ticket machine - No response when I tried right click.
Paygate - Can be set the price, but no redstone response.
Kiosk - Can't insert tickets. I think that isn't ticket by ticket machine.

I have attached a video as zip file. Can you help me?

### To Reproduce

[2022-12-19 21-20-53.zip](https://github.com/Lightman314/LightmansCurrencyFabric/files/10259310/2022-12-19.21-20-53.zip)

### Screenshots/Logs/Crash Reports

None

**Comment by Lightman314** [comment]
Fixed in v1.0.0.5. Thank you for reporting.

**Comment by minie0** [comment]
paygate didn't set tickets. Did you know?

**Comment by Lightman314** [comment]
Paygate does indeed let you set a ticket trade by clicking on the price input portion of the button with a valid "Master Ticket".
