### ISSUE TITLE
Crash: cannot cast to class

### ISSUE THREAD

**Issue by gonggong666** [Lightman314/LightmansCurrencyFabric#8]
### Minecraft Version

1.19.2

### Fabric Version

0.14.11

### Lightman's Currency Version

1.0.0.5

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

fabric-chunkpregen-0.3.5.jar
mythicmetals-0.16.4+1.19.2.jar
mcda-2.2.0.jar

### Describe the bug

Crashes when loading specific unidentified chunks.

### To Reproduce

Try pregenerating or exploring the world, some chunks will crash it

### Screenshots/Logs/Crash Reports

[2022-12-29-6.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/10320153/2022-12-29-6.log)

**Comment by Lightman314** [comment]
Fixed in v1.0.0.6. Thank you for reporting the issue :)
