### ISSUE TITLE
modpack authorization

### ISSUE THREAD

**Issue by lostopkk** [Lightman314/LightmansCurrencyFabric#9]
### Minecraft Version

1.19.2

### Fabric Version

0.14.12

### Lightman's Currency Version

1.0.0.6

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

I come to this issue that your model is magnificent, splendid and incredible. I would love to see this mod in my decoration modpack to have a good way to exchange between players, could I add it with your permission?

### To Reproduce

the modpack: https://modrinth.com/modpack/decoration-perfomance

### Screenshots/Logs/Crash Reports

.

**Comment by Lightman314** [comment]
So long as it works by downloading it from the official curseforge page, I don't care what modpacks it gets included in. If it requires that the mod files gets re-uploaded somewhere else though, I'm afraid that I'm gonna have to say no to that.

**Comment by lostopkk** [comment]
you can rest assured, your mod is unique! Thank you for the comment and resolve what needs to be resolved!

edit: Sorry I was still trying to understand what you said (I'm Portuguese so I had to translate later), yes I'll be able to download it via curseforge and put it in the modpack without any problems, now I understand thank you very much for the authorization and keep working on this amazing mod
